#+title: Kubernetes from boot.dev
#+author: mbrignall
#+date: 2026-04-13

Learning from the Kubernetes course as a refresher. Have k8s running on home server, want deeper knowledge.

No spoilers intended, just recording for reference and personal development goals. I have a Nix Darwin setup on MacBook Pro. I had to do some extra steps to get colima, docker and the kubernetes tools working nicely which I cover below.

* CH-1 Install and Setup

** Levels 1-3: Setup on Nix Darwin

Set up this repo and follow the first part of the course.

Context: I'm using nix darwin so had to jump through a few steps in advance before I could continue with the course:

Steps taken:

Once created ~flake.nix~ I also included a ~.envrc~ file with a single line: ~use flake~ which points the direnv to the flake.nix file. This means when I open the files in the repo directory it instantly loads the packages in the flake and provides docker/minikube environments.

~minikube start --extra-config="apiserver.cors-allowed-origins=['http://boot.dev']"~

Run the minikube in a 'detached' state:

~minikube dashboard --port=63840 > /dev/null 2>&1 &~

With that we have Nix flake with colima running docker running minikube - excellent!

** Level 4: Minikube and deployment

- Installing the boot.dev CLI

I followed the instruction on the repo for this one but used Nix for the Go installation which was just adding go to the list of packages and then updating ~.zshrc~ in the guide on the following link:

- [[https://github.com/bootdotdev/bootdev][bootdev CLI]]

Once I completed the instructions it was a simple case of using the login command and then I had access to use the CLI commands in the tutorial.

Running the commands came with success:

All tests passed! 🎉

Return to your browser to continue with the next lesson.

** Level 5: Deploying Synergy Chat

Following the guide I saw commands similar to those I'm using for my 'media' homelab cluster. After getting the pod name I was able to port forward to 8080 allowing me to visit the chat app in my browser.

~kubectl get pods~

and

~kubectl port-forward PODNAME 8080:8080~

To forward the port of the PODNAME (replaced by the output of the first command)
Once again the satisfying outcome:

All tests passed! 🎉

Return to your browser to continue with the next lesson.

** Levels 6-7: Minikube vs. Prod

This is a multi choice answer that comes from reading, and understanding Kubernetes and why Minikube does not work for large deployments across multiple nodes and applications.

That's day one, I'll continue into CH-2: Pods tomorrow.

* CH-2: Pods

** Levels 1-3: Pods and their ephemeral nature

Here we learned about the unique features of pods - that they are flexible and resilient and by design ephemeral. Also we learned how to replicate pods by editing the deployment config file. We also deleted a pod to see it respawn.

** Level 4: Unique IP addresses

Kubernetes pods all get allocated a unique IP address and can be found by using the following command:

~kubectl get pods -o wide~

This part of the course also introduced the use of the kubectl proxy serving details of the pods running in json format.

* CH-3: Deployments

** Level 1: Deployments

Editing the yaml config file to increase the replicas to 10 and using ~kubectl get pods~ to find they're all active and running. Deployment of many is simple!

** Level 2-3: Replica Sets

As mentioned, Replica Sets are rapped into the deployment configuration, but are mentioned and shown as a command for awareness. You will generally interact at the deployment level.

~kubectl get replicasets~

** Level 4: YAML config

Because we all love it.

Getting the deployments yaml file is simple with:

~kubectl get deployment synergychat-web -o yaml > web-deployment.yaml~

Once the file is edited, here I changed the replicas from 10 to 3, I'm going to run the command to apply changes:

~kubectl apply -f web-deployment.yaml~

Downloading the yaml config file from the deployment and reapplying got rid of the errors and now the deployment is up to date.

** Level 5: API Service

Here I'm getting to creating a yaml file for a second service. After following the requirements and using the [[https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#creating-a-deployment][reference docs]] I applied the changes and the new service is running!

** Level 6: Thrashing pods

When a pod's status is CrashLoopBackoff, that means the container is crashing (the program is exiting with error code 1).
* CH-4: ConfigMaps

** Level 1: ConfigMaps

Here I am applying a ConfigMap for the newly created API service, other applications for ConfigMaps:

- Ports
- URLs of other services
- Feature flags
- Settings that change between environments, like DEBUG mode

** Level 2: Applying the ConfigMap

Mapping the ~API_PORT~ to 8080: ~kubectl port-forward <pod-name> 8080:8080~

** Levels 3-4: ConfigMaps are insecure

As mentioned above ConfigMaps only apply to things you're happy with being visible to everyone with access to the cluster.

** Level 5: Crawler

I deployed a new service for the Crawler: This is an application that continuously crawls Project Gutenberg and exposes the juicy data that it finds via a JSON API.

Add some new environment variables:

#+begin_src yaml
  CRAWLER_PORT: "8080"
  CRAWLER_KEYWORDS: love,hate,joy,sadness,anger,disgust,fear,surprise
#+end_src

We can use the envFrom key instead of the env key to reference the entire config map and make it available to the pods in the deployment:

#+begin_src yaml
  envFrom:
  - configMapRef:
      name: synergychat-crawler-configmap
#+end_src

Here I hit a bit of a roadblock as I mistakenly didn't change the deployment name to the new crawler name after copying the file. This created an erroring pod that I had to then remove. Deleting the pod just restarted it so I eventually worked out that I had to delete the deployment:

~kubectl delete deployment synergychat-api~

Once I had removed the deployment and then reapplied the file the error was fixed and I was able to complete the module.

#+begin_src 
  NAME                                   READY   STATUS             RESTARTS     AGE
  synergychat-api-6c7dc8495b-vt6rt       0/1     CrashLoopBackOff   1 (6s ago)   10s
  synergychat-api-6c8d555cd6-494zs       1/1     Running            0            3m57s
#+end_src

With that the section was complete.

* CH-5: Services

** Level 1: Services

This one introduces new 'service' to the cluster. I followed the guide and was getting issues when attempting the port command:

~kubectl port-forward service/web-service 8080:80~

For this I ascertained that the port was in use but I could work out off the bat how to check that.

#+begin_src
    $ kubectl port-forward service/web-service 8080:80

    Unable to listen on port 8080: Listeners failed to create with the following errors: [unable to create listener: Error listen tcp4 127.0.0.1:8080: bind: address already in use unable to create listener: Error listen tcp6 [::1]:8080: bind: address already in use]
#+end_src

After a search I found that I could grep ps for this:

~ps -ef | grep port-forward~

Which helped identify the crawler was forwarding to port 8080 which was conflicting with this new command.

I used ps kill to stop the port forwarding, that may cause issues down the line but for now it fixed the issue of completing this service challenge.

** Level 2-3: Service Types

This was multi-choice questions based on the course material.

** Level 4: API Service

Here I created a API service for serving front-end assets using the template from the web-service.

** Level 5: Crawler Service

Added a crawler service here that used the default ClusterIP type.

** Level 6: Change the API Service

As it stated the API service is moving back to the ClusterIP type.

And that's the end of this module! yes.

* CH-6: Gateway

** Level 1: Gateway

Here I created files for the main gateway:

- ~api-httproute.yaml~
- ~app-gateway.yaml~
- ~app-gatewayclass.yaml~
- ~web-httproute.yaml~

Note: Always apply your changes ;)

** Level 2: DNS

Setting ~/etc/hosts/~ to include the entries needed to resolve our ~synchat.internal~ and ~synchatapi.internal~ domains locally.

** Level 3: Tunnel

Set up a tunnel to forward traffic to my cluster:

~minikube tunnel -c~

** Level 3-4: Gateway Types

This is teaching all about gateway types, adding the link below for ref:

- [[https://cloud.google.com/kubernetes-engine/docs/how-to/deploying-gateways][Gateway Docs]]

** Level 6: Chat

I got lost on this one, because I mapped the config correctly and got the deployment updated but something wasn't right as the chat couldn't call the API. I was getting errors in the browser console, looking for messages. I could not work it out for a while, but then I went over the files with a fine toothed comb and the error occurred when I copied the other service file as advised. I forgot to change ~selector/app~ to ~synergychat-api~ from the other file. That fixed everything.

With that sorted I am no able to move on. Phew!

* CH-7: Storage

** Level 1: Storage in Kubernetes

Here I added a new configmap entry for the db that will be used to store the messages and updated the deployment. Then observed after deleting the pod the outcome/affect on the stored messages.

** Level 2: Ephemeral Volumes

This was quite a challenge when it came to adding extra containers but when I sat back and actually read what was required it came together in the end. Note: Always READ the logs :D

** Levels 3-4: Containers in pods

This helped me understand how containers work in pods and the separation of configmap and resources.

** Level 5: Persistence

Now there is a persistent volume in the deployment cluster.

** Level 6-7: Attach Persistence

Following creation this module shows how to connect/attach the persistent volume to the deployment. I updated the config for both the deployment and the configmap and we're good to go. Data is persistent.

** Level 8: Databases

Learning when to use Kubernetes and other DB options is covered here. Use a DB for prod, like.

